### ISSUE TITLE
Player Administration issue with BOTH Beta versions

### ISSUE THREAD

**Issue by LargeCarTrucker** [LaserHydra/Backpacks#31]
When trying to access player backpacks after updating to the beta with current version of Player Administration an admin is unable to view a backpack of a player.

**Comment by WheteThunger** [comment]
I replied to a thread about this in the Player Administration help forum.
https://umod.org/community/player-administration/46516-support-for-backpacks-beta

It's not an issue with Backpacks. Yes, it's due to a change in Backpacks, but the issue is that Player Administration is depending on calling an internal function of Backpacks that has never been documented as an API. The correct solution is for Player Administration to invoke the `viewbackpack <steam id>` command, which is compatible with current and future versions of the Backpacks plugin.

**Comment by WheteThunger** [comment]
I've created a PR to resolve this in Player Administration. I'll also be updating both betas for compatibility anyway.

https://github.com/thibmo/PlayerAdministration/pull/16

**Comment by LargeCarTrucker** [comment]
Thanks White Thunder
